version: '3.8'

services:
  generaliste_tv_addon:
    build: .
    container_name: generaliste-tv-addon-stremio
    ports:
      - "7000:7000" # Mappe le port 7000 du conteneur au port 7000 de l'hôte
    restart: unless-stopped
